import { ConfigSchema } from '@server-manager/shared';

export const PalworldConfigSchema: ConfigSchema = {
  ServerName: {
    type: 'string',
    label: 'Server Name',
    description: 'Name of the server displayed in the server list',
    defaultValue: 'Default Palworld Server',
  },
  ServerDescription: {
    type: 'string',
    label: 'Server Description',
    description: 'Description of the server',
    defaultValue: '',
  },
  ServerPassword: {
    type: 'string',
    label: 'Server Password',
    description: 'Password required to join the server',
    defaultValue: '',
  },
  AdminPassword: {
    type: 'string',
    label: 'Admin Password',
    description: 'Password for admin access',
    defaultValue: '',
  },
  ServerPlayerMaxNum: {
    type: 'number',
    label: 'Max Players',
    description: 'Maximum number of players',
    min: 1,
    max: 32,
    defaultValue: 32,
  },
  PublicPort: {
    type: 'number',
    label: 'Public Port',
    description: 'Game port',
    defaultValue: 8211,
  },
  PublicIP: {
    type: 'string',
    label: 'Public IP',
    description: 'Public IP address',
    defaultValue: '',
  },
  RCONEnabled: {
    type: 'boolean',
    label: 'RCON Enabled',
    description: 'Enable RCON',
    defaultValue: false,
  },
  RCONPort: {
    type: 'number',
    label: 'RCON Port',
    description: 'RCON port',
    defaultValue: 25575,
  },
  DayTimeSpeedRate: {
    type: 'number',
    label: 'Day Time Speed Rate',
    description: 'Day time speed multiplier',
    min: 0.1,
    max: 5,
    defaultValue: 1.0,
  },
  NightTimeSpeedRate: {
    type: 'number',
    label: 'Night Time Speed Rate',
    description: 'Night time speed multiplier',
    min: 0.1,
    max: 5,
    defaultValue: 1.0,
  },
  ExpRate: {
    type: 'number',
    label: 'EXP Rate',
    description: 'Experience multiplier',
    min: 0.1,
    max: 20,
    defaultValue: 1.0,
  },
  PalCaptureRate: {
    type: 'number',
    label: 'Pal Capture Rate',
    description: 'Pal capture rate multiplier',
    min: 0.1,
    max: 2,
    defaultValue: 1.0,
  },
  DeathPenalty: {
    type: 'select',
    label: 'Death Penalty',
    description: 'Penalty on death',
    options: ['None', 'Item', 'ItemAndEquipment', 'All'],
    defaultValue: 'All',
  },
};
